extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parser: "@typescript-eslint/parser"
parserOptions:
  project: true
  tsconfigRootDir: __dirname
plugins:
  - "@typescript-eslint"
root: true
env:
  node: true
ignorePatterns:
  - .eslintrc.yml
rules:
  semi:
    - error
    - never
  indent:
    - error
    - 4
  space-infix-ops:
    - error
  no-multi-spaces:
    - error